# è…¾è®¯äº‘å‡­è¯ SecretIdï¼ŒğŸ‘‰ https://console.cloud.tencent.com/cam/capi
secretId: 

# è…¾è®¯äº‘å‡­è¯ SecretKey, ğŸ‘‰ https://console.cloud.tencent.com/cam/capi
secretKey:

# äº‘å¼€å‘ç¯å¢ƒIDï¼Œå¯åœ¨è…¾è®¯äº‘äº‘å¼€å‘æ§åˆ¶å°è·å–
envId:
